name: Publish Docker image to GHCR

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Image version (e.g., 1.0.0)"
                required: true
                type: string

jobs:
    build-and-push-to-ghcr:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{github.actor}}/http-range-server:${{ inputs.version }}
